local config = {
	enabled_modules = {
		retrievehands = true,
		deckthebalatro = true,
		suitedunimpresseddispleasedoverlord = false,
		dankranks = false, --not real
		skinmeadeck = true,
		enhancable = true,
		vouchme = true,
		moreconsumables = true,
		basicoddities = true,
		blindtoallbutthevideo = true,
		tagimit = true, --soon(tm)
		jokerstamps = true,
		lookslikethejokers = true,
		editiontomeetya = true,
		hamspect = true,
	},
	enabled_jokers = {
		wacky_joker = false,
		crass_joker = false,
		obnoxious_joker = false,
		immature_joker = false,
		funny_number = false,
		bracket = false,
		court_joker = false,
		regal_joker = false,
		royal = false,
		gift_from_the_void = true,
		lord_of_the_meek = true,
		mirage_joker = true,
		transfusion = true,
		placeholder_joker = true,
		garden = true,
		menagerie = false,
	},
	enabled_consumables = {
		--tarot
		universe = true,
		void = true,
		happy_squirrel = true,
		artist = true,
		veteran = true,
		juggler = false,
		drunkard = true,
		joker = true,
		page_of_cups = false,
		page_of_wands = false,
		page_of_coins = false,
		page_of_swords = false,
		
		--planets
		comet = true,
		meteor = true,
		satellite = true,
		moon = true,
		station = true,
		dysnomia = true,
		planet_s = true,
		planet_h = true,
		planet_c = true,
		planet_d = true,
		nice_planet = false,
		castle_planet = false,
		blaze_planet = false,
		twice_nice_planet = false,
		skeet_planet = false,
		little_dog_planet = false,
		big_dog_planet = false,
		little_cat_planet = false,
		big_cat_planet = false,
		blaze_house_planet = false,
		flushblaze_planet = false,
		spectrumblaze_planet = false,
		castle_flush_planet = false,
		castle_spectrum_planet = false,
		skeet_flush_planet = false,
		skeet_spectrum_planet = false,
		blaze_five_planet = false,
		flushblaze_house_planet = false,
		spectrumblaze_house_planet = false,
		flushblaze_five_planet = false,
		spectrumblaze_five_planet = false,
		castle_stone_planet = false,
		castle_gold_planet = false,
		castle_steel_planet = false,
		castle_glass_planet = false,
		
		--spectrals
		chance = true,
		offering = true,
		tribute = true,
		sacrifice = true,
		scry = true,
		lotus = true,
		phantom = true,
		-- following require jokerstamps and respective stamp if applicable
			mischief = true,
			comedy = true,
			tragedy = true,
			whimsy = true,
			entropy = true,
			wonder = true,
			macabre = true,
			duplicity = true,
			banana = true,
			artifice = true,
		
		--oddities
		-- following requires oddityapi
		one_jollar = true,
		two_jollar = true,
		five_jollar = true,
		ten_jollar = true,
		twenty_jollar = true,
		pot_of_joker = true,
		green_chip = true,
		yellow_chip = true,
		red_blue_chip = true,
		purple_chip = true,
		power_chip = true,
		silica_packet = true,
		jimbobread_man = true,
		jimbobread_man_half = true,
		narwhal_horn = true,
		cultist_potion = true,
		fire_potion = true,
		snecko_potion = true,
		energy_potion = true,
		vote_sticker = true,
		cpu_memory = true,
		estradiol = true,
		faded_voucher = true,
	},
	enabled_vouchers = {
		spectral_merchant = true,
		spectral_tycoon = true,
		-- following requires jokerstamps
		stamp_savvy = true,
		stamp_coupon = true,
		-- following requires oddityapi
		oddity_merchant = true,
		oddity_tycoon = true,
	},
	enabled_seals = {
	},
	enabled_stamps = {
		jimbo = true,
		todd = true,
		steven = true,
		chaos = true,
		andy = true,
		mr_bones = true,
		vampire = false,
		sock_and_buskin = true,
		hiker = false,
		gros_michel = true,
		blueprint = true,
	},
	enabled_enhancements = {
		loop = false,
		grass = true,
		dirt = true,
		star = true,
	},
	enabled_editions = {
		gilded = true,
	},
	enabled_decks = {
		collectors_deck = true,
		arcane_deck = true,
		alpha_deck = true,
		beta_deck = true,
		omega_deck = true,
	},
	enabled_suits = {
		Cups = false,
		Wands = false,
		Coins = false,
		Swords = false,
		Light = false,
		Mind = false,
		Rage = false,
		Time = false,
		Breath = false,
		Life = false,
		Void = false,
		Heart = false,
		Hope = false,
		Space = false,
		Blood = false,
		Doom = false,
		Pickaxes = false,
	},
	enabled_deckskins = {
		diamond_pickaxe = false,
	},
	enabled_blinds = {
		fehu = true,
		uruz = true,
		thorn = true,
		ansuz = true,
		raido = true,
		kaun = true,
		gyfu = true,
		wynn = true,
		hagalaz = true,
		naudiz = true,
		isaz = true,
		jera = true,
		eihaz = true,
		pertho = true,
		algiz = true,
		sowilo = true,
		tiwaz = true,
		berkanan = true,
		ehwaz = true,
		mannaz = true,
		laguz = true,
		ingwaz = true,
		dagaz = true,
		othala = true,
	},
	enabled_hands = {
		nice = false,
		blaze = false,
		twice_nice = false,
		skeet = false,
		little_dog = false,
		big_dog = false,
		little_cat = false,
		big_cat = false,
		castle = false,
		blaze_house = false,
		flushblaze = false,
		spectrumblaze = false,
		castle_flush = false,
		castle_spectrum = false,
		skeet_flush = false,
		skeet_spectrum = false,
		blaze_five = false,
		flushblaze_house = false,
		spectrumblaze_house = false,
		flushblaze_five = false,
		spectrumblaze_five = false,
		castle_stone = false,
		castle_gold = false,
		castle_steel = false,
		castle_glass = false,
	},
	enabled_tags = {
		gilded = true,
	},
	enabled_aspects = {
		heart = true,
	},
	mechanics = {
		minor_arcana_flush_effects = true,
		all_hands_are_secret = false,
	},
	starting_deck = {
		allowed_suits = {
			['Hearts'] = true,
			['Clubs'] = true,
			['Diamonds'] = true,
			['Spades'] = true,
			['thac_Cups'] = false,
			['thac_Wands'] = false,
			['thac_Coins'] = false,
			['thac_Swords'] = false,
			['thac_Light'] = false,
			['thac_Mind'] = false,
			['thac_Rage'] = false,
			['thac_Time'] = false,
			['thac_Breath'] = false,
			['thac_Life'] = false,
			['thac_Void'] = false,
			['thac_Heart'] = false,
			['thac_Hope'] = false,
			['thac_Space'] = false,
			['thac_Blood'] = false,
			['thac_Doom'] = false,
			['thac_Pickaxes'] = false,
		},
		allowed_ranks = {
			['0'] = false,
			['1'] = false,
			['2'] = true,
			['3'] = true,
			['4'] = true,
			['5'] = true,
			['6'] = true,
			['7'] = true,
			['8'] = true,
			['9'] = true,
			['10'] = true,
			['Jack'] = true,
			['Queen'] = true,
			['King'] = true,
			['Ace'] = true,
			['11'] = false,
			['12'] = false,
			['13'] = false,
			['14'] = false,
			['15'] = false,
			['16'] = false,
			['17'] = false,
			['18'] = false,
			['19'] = false,
			['20'] = false,
			['Cavalier'] = false,
			['Bishop'] = false,
			['Rook'] = false,
			['21'] = false,
			['22'] = false,
			['23'] = false,
			['24'] = false,
			['25'] = false,
			['26'] = false,
			['27'] = false,
			['28'] = false,
			['29'] = false,
			['30'] = false,
			['Viscount'] = false,
			['Marquess'] = false,
			['Duke'] = false,
			['Thorn'] = false,
			['Oracle'] = false,
		},
	},
	
	
	testing_kit = false,
	test_hands = false,
}

return config
